<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxXFxPX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxXFxPX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxXFxPX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxXFxPX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxXFxPX\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxXFxPX',
    'container.build_id' => '6e9b2079',
    'container.build_time' => 1695039227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxXFxPX');
